# Generated by Django 4.2.20 on 2025-06-27 14:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=30, null=True, verbose_name='Кто оставил отзыв')),
                ('comment', models.TextField(max_length=250, verbose_name='Отзыв')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название салона')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Контактный телефон')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('image', models.ImageField(blank=True, upload_to='media/salon_img/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Услуга')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Мастер')),
                ('image', models.ImageField(blank=True, upload_to='media/master_img/', verbose_name='Картинка')),
                ('specialty', models.CharField(blank=True, max_length=35, verbose_name='Специальность')),
                ('experience_at', models.DateField(blank=True, max_length=35, null=True, verbose_name='Опыт')),
                ('salons', models.ManyToManyField(blank=True, related_name='masters', to='beauty_salon.salon', verbose_name='Салоны работы')),
                ('services', models.ManyToManyField(blank=True, related_name='masters', to='beauty_salon.service', verbose_name='Оказываемые услуги')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/avatars/')),
                ('personal_data_consent', models.BooleanField(default=False, verbose_name='Согласие ОПД')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('recorded', 'Записан'), ('completed', 'Выполнен'), ('canceled', 'Отменен'), ('call', 'Консультация')], default='recorded', max_length=20, verbose_name='Статус записи')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя клиента')),
                ('payment', models.CharField(blank=True, choices=[('cash', 'Наличностью'), ('e_pay', 'Электронно')], default='cash', max_length=15, null=True, verbose_name='Тип оплаты')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата записи')),
                ('time', models.CharField(blank=True, choices=[('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00')], max_length=20, null=True, verbose_name='Время записи')),
                ('comment', models.TextField(blank=True, max_length=250, null=True, verbose_name='Комментарий')),
                ('personal_data_consent', models.BooleanField(default=False, verbose_name='Согласие ОПД')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beauty_salon.client', verbose_name='Клиент')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='beauty_salon.master', verbose_name='Мастер')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon_appointments', to='beauty_salon.salon', verbose_name='Салон')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_appointments', to='beauty_salon.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
