# Generated by Django 4.2.20 on 2025-06-27 21:55

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='contact_tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='beauty_salon.master', verbose_name='Мастер'),
        ),
    ]
