# Generated by Django 4.2.20 on 2025-06-26 10:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('recorded', 'Записан'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='recorded', max_length=20, verbose_name='Статус записи')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time_at', models.CharField(blank=True, choices=[('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00')], max_length=20, null=True, verbose_name='Время записи')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_services', to='beauty_salon.appointment', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'элемент записи',
                'verbose_name_plural': 'элементы записи',
            },
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='master',
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='salon',
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='salonserviceprice',
            options={'verbose_name': 'Услуга в салоне', 'verbose_name_plural': 'Услуги в салоне'},
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='masters', to='beauty_salon.service', verbose_name='Оказываемые услуги'),
        ),
        migrations.AlterField(
            model_name='salonserviceprice',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_prices', to='beauty_salon.master', verbose_name='Мастер'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderService',
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='beauty_salon.master', verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_appointments', to='beauty_salon.salon', verbose_name='Салон'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_appointments', to='beauty_salon.service', verbose_name='Услуга'),
        ),
    ]
