# Generated by Django 4.2.20 on 2025-06-26 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderservice',
            options={'ordering': ['record_date', 'record_time_at'], 'verbose_name': 'элемент записи', 'verbose_name_plural': 'элементы записи'},
        ),
        migrations.AddField(
            model_name='orderservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderservice',
            name='record_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата записи'),
        ),
    ]
