# Generated by Django 4.2.20 on 2025-06-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0002_feedback_contact_tel_feedback_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/service_img/', verbose_name='Картинка'),
        ),
    ]
