# Generated by Django 4.2.20 on 2025-06-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0002_appointment_appointmentservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='salons',
            field=models.ManyToManyField(blank=True, related_name='masters', to='beauty_salon.salon', verbose_name='Салоны работы'),
        ),
    ]
