# Generated by Django 4.2.20 on 2025-06-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0003_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='media/avatars/'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.FileField(blank=True, upload_to='media/salon_img/', verbose_name='Картинка'),
        ),
    ]
