# Generated by Django 4.2.20 on 2025-06-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0004_client_delete_userprofile_appointment_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=30, null=True, verbose_name='Кто оставил отзыв')),
                ('comment', models.TextField(max_length=250, verbose_name='Отзыв')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.CharField(blank=True, choices=[('cash', 'Наличностью'), ('e_pay', 'Электронно')], default='cash', max_length=15, null=True, verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='personal_data_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие ОПД'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('recorded', 'Записан'), ('completed', 'Выполнен'), ('canceled', 'Отменен'), ('call', 'Консультация')], default='recorded', max_length=20, verbose_name='Статус записи'),
        ),
    ]
