# Generated by Django 4.2.20 on 2025-06-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0004_remove_salon_latitude_remove_salon_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('waiting', 'Ожидает подтверждения'), ('paid', 'Оплачено'), ('failed', 'Ошибка оплаты')], default='pending', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа ЮKassa'),
        ),
    ]
