# Generated by Django 4.2.20 on 2025-06-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0005_feedback_appointment_comment_appointment_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='experience_at',
            field=models.DateField(blank=True, max_length=35, null=True, verbose_name='Опыт'),
        ),
        migrations.AddField(
            model_name='master',
            name='specialty',
            field=models.CharField(blank=True, max_length=35, verbose_name='Специальность'),
        ),
    ]
