# Generated by Django 4.2.20 on 2025-06-26 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0006_master_experience_at_master_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='beauty_salon.master', verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon_appointments', to='beauty_salon.salon', verbose_name='Салон'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_appointments', to='beauty_salon.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank=True, choices=[('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00')], max_length=20, null=True, verbose_name='Время записи'),
        ),
        migrations.DeleteModel(
            name='AppointmentService',
        ),
    ]
