# Generated by Django 4.2.20 on 2025-06-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0007_appointment_client_name_appointment_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='salon',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
