# Generated by Django 4.2.20 on 2025-06-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0008_salon_latitude_salon_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalonServicePrice',
        ),
    ]
